require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/habit_activities", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # HabitActivity. As you add validations to HabitActivity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { activity_count: 30 }
  }

  let(:invalid_attributes) {
    # skip("Add a hash of attributes invalid for your model")
    { activitycount: nil }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # HabitActivitiesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      HabitActivity.create! valid_attributes
      get api_v1_habit_activities_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      habit_activity = HabitActivity.create! valid_attributes
      get api_v1_habit_activity_url(habit_activity), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HabitActivity" do
        expect {
          post api_v1_habit_activities_url,
               params: { habit_activity: valid_attributes }, headers: valid_headers, as: :json
        }.to change(HabitActivity, :count).by(1)
      end

      it "renders a JSON response with the new habit_activity" do
        post api_v1_habit_activities_url,
             params: { habit_activity: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HabitActivity" do
        expect {
          post api_v1_habit_activities_url,
               params: { habit_activity: invalid_attributes }, as: :json
        }.to change(HabitActivity, :count).by(0)
      end

      it "renders a JSON response with errors for the new habit_activity" do
        post api_v1_habit_activities_url,
             params: { habit_activity: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  # Below test cases are invalid as on now since the actions are not defined - Enable if needed later

  # describe "PATCH /update" do
  #   context "with valid parameters" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested habit_activity" do
  #       habit_activity = HabitActivity.create! valid_attributes
  #       patch habit_activity_url(habit_activity),
  #             params: { habit_activity: new_attributes }, headers: valid_headers, as: :json
  #       habit_activity.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "renders a JSON response with the habit_activity" do
  #       habit_activity = HabitActivity.create! valid_attributes
  #       patch habit_activity_url(habit_activity),
  #             params: { habit_activity: new_attributes }, headers: valid_headers, as: :json
  #       expect(response).to have_http_status(:ok)
  #       expect(response.content_type).to match(a_string_including("application/json"))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "renders a JSON response with errors for the habit_activity" do
  #       habit_activity = HabitActivity.create! valid_attributes
  #       patch habit_activity_url(habit_activity),
  #             params: { habit_activity: invalid_attributes }, headers: valid_headers, as: :json
  #       expect(response).to have_http_status(:unprocessable_entity)
  #       expect(response.content_type).to match(a_string_including("application/json"))
  #     end
  #   end
  # end

  # describe "DELETE /destroy" do
  #   it "destroys the requested habit_activity" do
  #     habit_activity = HabitActivity.create! valid_attributes
  #     expect {
  #       delete habit_activity_url(habit_activity), headers: valid_headers, as: :json
  #     }.to change(HabitActivity, :count).by(-1)
  #   end
  # end
end
